# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'HomeCarePlus' do
  config = use_native_modules!

  # Required for @react-native-firebase/* on RN 0.81: Firebase's Swift pods
  # (e.g. FirebaseCoreInternal) import GoogleUtilities, which does not declare
  # DEFINES_MODULE. Under CocoaPods' default static linkage that import fails
  # to resolve. use_frameworks! forces every pod to build as a framework,
  # which always gets a module map, resolving it. See https://rnfirebase.io/ios-spm
  use_frameworks! :linkage => :dynamic

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
