export interface LegalSection {
  title: string;
  paragraphs: string[];
}

export interface PrivacyPolicyLanguageContent {
  lastUpdated: string;
  sections: LegalSection[];
}

export const PRIVACY_POLICY_CONTENT: Record<'en' | 'ar', PrivacyPolicyLanguageContent> = {
  en: {
    lastUpdated: 'Effective Date: 29/07/2026',
    sections: [
      {
        title: 'Introduction',
        paragraphs: [
          'Welcome to Home Care Plus.',
          "Recognizing the importance of protecting personal information and maintaining the confidentiality of customer data, Home Care Plus is committed to safeguarding all information provided by customers. This Privacy Policy explains how we collect, use, store, retain, protect, and disclose customer information. This Privacy Policy forms an integral part of the Company's Terms and Conditions. By accessing, registering with, or using our website, mobile application, or services, the customer acknowledges that they have read, understood, and accepted this Privacy Policy.",
        ],
      },
      {
        title: '1. Customer Information',
        paragraphs: [
          'For the purposes of this Privacy Policy, "Customer Information" includes, but is not limited to:',
          '• Full Name',
          '• Mobile Phone Number',
          '• Email Address (where applicable)',
          '• Residential or Service Address',
          '• Payment Information (such as payment method details; complete payment card information is processed securely by authorized payment providers and is not stored unless required by law or operational necessity)',
          '• Geographical Location Data for providing location-based services',
          '• Booking and Service History',
          '• Device Information (such as device model, operating system version, application version, crash reports, and diagnostic information)',
          '• Push Notification Preferences',
          "• Any additional information voluntarily provided by the customer while using the Company's services.",
        ],
      },
      {
        title: '2. Collection, Storage and Retention of Information',
        paragraphs: [
          '2.1 Information Collection',
          'The customer agrees that the Company may collect personal information, contact details, booking information, service requests, transaction records, and updates related to interactions with the Company for the purpose of providing and improving its services.',
          'Information may be collected through:',
          '• The Home Care Plus mobile application',
          "• The Company's website",
          '• Customer support interactions',
          '• Booking requests',
          '• Payment transactions',
          '• Location services (where permission has been granted)',
          '• Push notification services',
          '• Authentication and security services',
          '2.2 Information Storage',
          'Customer information is stored on servers designated by the Company within the Kingdom of Saudi Arabia or through secure cloud service providers approved by the Company.',
          'The Company implements appropriate administrative, organizational, and technical security measures to protect customer information against unauthorized access, alteration, disclosure, misuse, or destruction, in accordance with applicable cybersecurity standards.',
          '2.3 Information Retention',
          'Customer information shall be retained for as long as required to:',
          '• Provide requested services',
          '• Maintain customer accounts',
          '• Comply with applicable laws and regulations',
          '• Resolve disputes',
          '• Prevent fraud',
          '• Protect the legitimate interests of the Company',
          'When customer information is no longer required, it shall be securely deleted, anonymized, or disposed of using appropriate security procedures.',
        ],
      },
      {
        title: '3. Use of Customer Information',
        paragraphs: [
          'Customer information may be used for the following purposes:',
          '• Providing requested home care services',
          '• Managing bookings and appointments',
          '• Customer identity verification',
          '• Processing payments',
          '• Providing customer support',
          '• Sending booking confirmations and service updates',
          '• Sending important service-related notifications',
          '• Improving application functionality and user experience',
          '• Fraud detection and prevention',
          '• Security monitoring',
          '• Internal reporting and business analytics',
          '• Compliance with legal and regulatory obligations',
        ],
      },
      {
        title: '4. Disclosure of Information',
        paragraphs: [
          'The Company may disclose customer information only where necessary and in accordance with applicable laws.',
          'Customer information may be shared with:',
          '• Authorized employees of the Company',
          '• Approved service providers',
          '• Payment service providers',
          '• Technical infrastructure providers',
          '• Cloud hosting providers',
          '• Government authorities when required by the laws and regulations of the Kingdom of Saudi Arabia',
          '• Business partners involved in delivering requested services',
          'Access to customer information is limited only to authorized personnel whose responsibilities require such access.',
          'The Company does not sell customer personal information to third parties.',
          'The Company may use anonymized or aggregated information for statistical analysis, reporting, service improvement, research, and business planning, provided such information does not identify any individual customer.',
          'The customer is solely responsible for ensuring the accuracy and correctness of the information provided to the Company.',
        ],
      },
      {
        title: '5. Information Security',
        paragraphs: [
          'The Company is committed to protecting customer information by implementing industry-standard cybersecurity measures and security controls.',
          'These measures include, where appropriate:',
          '• Secure encrypted communication channels (HTTPS/TLS)',
          '• Encryption of sensitive information during transmission',
          '• Access control and authentication mechanisms',
          '• Continuous monitoring of systems',
          '• Protection against unauthorized access, modification, disclosure, or destruction of customer information',
          '• Regular security updates and vulnerability management',
          'Although the Company implements reasonable security measures, no electronic storage or transmission method can be guaranteed to be completely secure.',
        ],
      },
      {
        title: '6. Customer Responsibility for Privacy Protection',
        paragraphs: [
          'Customers are responsible for protecting their own personal information.',
          'Customers should:',
          '• Keep their account credentials confidential.',
          '• Never share OTP verification codes with any person.',
          '• Avoid sharing sensitive personal information through unsecured communication channels.',
          '• Use trusted devices when accessing Company services.',
          '• Keep operating systems and antivirus software updated.',
          '• Notify the Company immediately if unauthorized access or suspicious activity is detected.',
        ],
      },
      {
        title: '7. External Links',
        paragraphs: [
          "The Company's website or mobile application may contain links to external websites or third-party services.",
          'The Company is not responsible for the privacy practices, security policies, or content of third-party websites. Customers should review the privacy policies of such websites before providing personal information.',
        ],
      },
      {
        title: '8. Confidentiality and Non-Disclosure',
        paragraphs: [
          '"Confidential Information" refers to information disclosed by the customer that is considered confidential and not publicly available.',
          'The Company shall maintain the confidentiality of such information and shall not disclose it except:',
          '• To authorized government authorities where required by applicable law.',
          '• To authorized service providers assisting the Company in operating its business.',
          '• To business partners where necessary to provide requested services.',
          '• For statistical or analytical purposes where customer identity cannot be determined.',
          "• With the customer's prior written consent.",
          'The obligation of confidentiality applies to all forms of disclosure, including oral, written, electronic, digital, and any other method of communication.',
          'The Company may use confidential information solely for improving its services, policies, operational efficiency, security, and customer experience.',
        ],
      },
      {
        title: '9. Cookies and Similar Technologies',
        paragraphs: [
          "The Company's website uses cookies and similar technologies to:",
          '• Improve user experience',
          '• Remember user preferences',
          '• Analyze website traffic',
          '• Improve website performance',
          '• Personalize website content',
          '• Improve marketing effectiveness where applicable',
          'Customers may manage or disable cookies through their browser settings. Disabling cookies may affect certain website functionalities.',
        ],
      },
      {
        title: '10. Mobile Application Permissions',
        paragraphs: [
          'The Home Care Plus mobile application may request access to certain device permissions to provide its services effectively.',
          'Depending on the features used, the application may request access to:',
          '• Device Location (to locate service addresses and display maps)',
          '• Camera (where required for service-related functionality)',
          '• Notifications (to provide booking updates and important service alerts)',
          '• Internet and Network Access',
          '• Device Information required for application security and diagnostics',
          'Permissions are requested only when necessary for the relevant functionality, and users may manage these permissions through their device settings.',
        ],
      },
      {
        title: '11. Third-Party Services',
        paragraphs: [
          'To provide and improve its services, the Company may utilize trusted third-party service providers, including but not limited to:',
          '• Authentication providers',
          '• Cloud hosting providers',
          '• Push notification services',
          '• Mapping and location service providers',
          '• Payment gateway providers',
          '• Analytics and crash reporting services',
          'These providers process customer information only as necessary to perform services on behalf of the Company and are expected to maintain appropriate security and confidentiality standards.',
        ],
      },
      {
        title: '12. Updating Customer Information',
        paragraphs: [
          'Customers are responsible for notifying the Company whenever their personal information changes.',
          'Where necessary, the Company may request additional verification before updating customer information if identity verification is required or fraudulent activity is suspected.',
          'Customers are solely responsible for any consequences arising from failure to maintain accurate and up-to-date personal information.',
        ],
      },
      {
        title: '13. Changes to this Privacy Policy',
        paragraphs: [
          'The Company reserves the right to amend, modify, or update this Privacy Policy at any time.',
          "Updated versions shall be published through the Company's official website or other official communication channels.",
          'Continued use of the Company\'s services after publication of the revised Privacy Policy constitutes acceptance of the updated Policy.',
        ],
      },
      {
        title: '14. Governing Law',
        paragraphs: [
          'This Privacy Policy shall be governed by and interpreted in accordance with the laws and regulations of the Kingdom of Saudi Arabia.',
          'Any dispute arising from or relating to this Privacy Policy shall fall under the exclusive jurisdiction of the competent judicial and regulatory authorities within the Kingdom of Saudi Arabia.',
        ],
      },
      {
        title: '15. Contact Us',
        paragraphs: [
          'If you have any questions regarding this Privacy Policy or your personal information, please contact us using the Company\'s official communication channels.',
          'Home Care Plus',
          'Website: https://hcare.plus',
          'Email: admin@hcare.plus',
          'Phone: +919747869897',
          'Address: Tc 24/3088, Ushasandya Building, Kowdiar Kaudiar, Thiruvananthapuram, Kerala, 695003',
          'By using the Home Care Plus website, mobile application, or any services provided by the Company, you acknowledge that you have read, understood, and agreed to this Privacy Policy.',
        ],
      },
    ],
  },
  ar: {
    lastUpdated: 'تاريخ السريان: 29/07/2026',
    sections: [
      {
        title: 'مقدمة',
        paragraphs: [
          'مرحبًا بكم في Home Care Plus.',
          'إيمانًا من Home Care Plus بأهمية حماية المعلومات الشخصية والحفاظ على سرية بيانات العملاء، تلتزم الشركة بحماية جميع المعلومات التي يقدمها العملاء. توضح سياسة الخصوصية هذه كيفية جمعنا لمعلومات العملاء واستخدامها وتخزينها والاحتفاظ بها وحمايتها والإفصاح عنها. تُعد سياسة الخصوصية هذه جزءًا لا يتجزأ من الشروط والأحكام الخاصة بالشركة. وباستخدامك أو تسجيلك أو وصولك إلى موقعنا الإلكتروني أو تطبيقنا أو خدماتنا، فإنك تقر بأنك قرأت وفهمت ووافقت على سياسة الخصوصية هذه.',
        ],
      },
      {
        title: '1. معلومات العميل',
        paragraphs: [
          'لأغراض سياسة الخصوصية هذه، تشمل "معلومات العميل"، على سبيل المثال لا الحصر:',
          '• الاسم الكامل',
          '• رقم الهاتف المحمول',
          '• البريد الإلكتروني (عند الاقتضاء)',
          '• عنوان السكن أو عنوان الخدمة',
          '• معلومات الدفع (مثل تفاصيل وسيلة الدفع؛ حيث تتم معالجة بيانات بطاقة الدفع الكاملة بشكل آمن من قبل مزودي خدمات الدفع المعتمدين ولا يتم تخزينها إلا إذا كان ذلك مطلوبًا بموجب القانون أو للضرورة التشغيلية)',
          '• بيانات الموقع الجغرافي لتقديم الخدمات المعتمدة على الموقع',
          '• سجل الحجوزات والخدمات',
          '• معلومات الجهاز (مثل طراز الجهاز، وإصدار نظام التشغيل، وإصدار التطبيق، وتقارير الأعطال، ومعلومات التشخيص)',
          '• تفضيلات الإشعارات الفورية',
          '• أي معلومات إضافية يقدمها العميل طواعية أثناء استخدام خدمات الشركة.',
        ],
      },
      {
        title: '2. جمع المعلومات وتخزينها والاحتفاظ بها',
        paragraphs: [
          '2.1 جمع المعلومات',
          'يوافق العميل على أنه يجوز للشركة جمع المعلومات الشخصية وبيانات الاتصال ومعلومات الحجز وطلبات الخدمة وسجلات المعاملات والتحديثات المتعلقة بالتفاعل مع الشركة، وذلك بغرض تقديم خدماتها وتحسينها.',
          'يمكن جمع المعلومات من خلال:',
          '• تطبيق Home Care Plus',
          '• الموقع الإلكتروني الخاص بالشركة',
          '• التفاعلات مع خدمة العملاء',
          '• طلبات الحجز',
          '• المعاملات المالية',
          '• خدمات الموقع (عند منح الإذن)',
          '• خدمات الإشعارات الفورية',
          '• خدمات التوثيق والأمان',
          '2.2 تخزين المعلومات',
          'يتم تخزين معلومات العميل على خوادم تحددها الشركة داخل المملكة العربية السعودية، أو من خلال مزودي خدمات سحابية آمنين معتمدين من قبل الشركة.',
          'تطبق الشركة تدابير أمنية إدارية وتنظيمية وتقنية مناسبة لحماية معلومات العميل من الوصول غير المصرح به أو التعديل أو الإفصاح أو سوء الاستخدام أو الإتلاف، وفقًا لمعايير الأمن السيبراني المعمول بها.',
          '2.3 الاحتفاظ بالمعلومات',
          'يتم الاحتفاظ بمعلومات العميل طالما كان ذلك ضروريًا من أجل:',
          '• تقديم الخدمات المطلوبة',
          '• إدارة حسابات العملاء',
          '• الامتثال للقوانين واللوائح المعمول بها',
          '• حل النزاعات',
          '• منع الاحتيال',
          '• حماية المصالح المشروعة للشركة',
          'عندما لا تعود معلومات العميل مطلوبة، يتم حذفها أو إخفاء هويتها أو التخلص منها بشكل آمن باستخدام إجراءات أمنية مناسبة.',
        ],
      },
      {
        title: '3. استخدام معلومات العميل',
        paragraphs: [
          'يجوز استخدام معلومات العميل للأغراض التالية:',
          '• تقديم خدمات الرعاية المنزلية المطلوبة',
          '• إدارة الحجوزات والمواعيد',
          '• التحقق من هوية العميل',
          '• معالجة المدفوعات',
          '• تقديم دعم العملاء',
          '• إرسال تأكيدات الحجز وتحديثات الخدمة',
          '• إرسال الإشعارات المهمة المتعلقة بالخدمة',
          '• تحسين وظائف التطبيق وتجربة المستخدم',
          '• كشف الاحتيال ومنعه',
          '• المراقبة الأمنية',
          '• التقارير الداخلية وتحليلات الأعمال',
          '• الامتثال للالتزامات القانونية والتنظيمية',
        ],
      },
      {
        title: '4. الإفصاح عن المعلومات',
        paragraphs: [
          'يجوز للشركة الإفصاح عن معلومات العميل فقط عند الضرورة ووفقًا للقوانين المعمول بها.',
          'يمكن مشاركة معلومات العميل مع:',
          '• الموظفين المخولين في الشركة',
          '• مزودي الخدمات المعتمدين',
          '• مزودي خدمات الدفع',
          '• مزودي البنية التحتية التقنية',
          '• مزودي الاستضافة السحابية',
          '• الجهات الحكومية عند الطلب بموجب أنظمة ولوائح المملكة العربية السعودية',
          '• الشركاء التجاريين المشاركين في تقديم الخدمات المطلوبة',
          'يقتصر الوصول إلى معلومات العميل على الموظفين المخولين الذين تتطلب مسؤولياتهم ذلك الوصول.',
          'لا تبيع الشركة معلومات العميل الشخصية لأطراف ثالثة.',
          'يجوز للشركة استخدام المعلومات المجهولة أو المجمّعة لأغراض التحليل الإحصائي والتقارير وتحسين الخدمات والبحث والتخطيط للأعمال، شريطة ألا تحدد هذه المعلومات هوية أي عميل بعينه.',
          'يتحمل العميل وحده مسؤولية التأكد من دقة وصحة المعلومات المقدمة إلى الشركة.',
        ],
      },
      {
        title: '5. أمن المعلومات',
        paragraphs: [
          'تلتزم الشركة بحماية معلومات العميل من خلال تطبيق تدابير أمن سيبراني وضوابط أمنية وفق أفضل المعايير المعتمدة في الصناعة.',
          'تشمل هذه التدابير، عند الاقتضاء:',
          '• قنوات اتصال آمنة ومشفرة (HTTPS/TLS)',
          '• تشفير المعلومات الحساسة أثناء النقل',
          '• آليات التحكم في الوصول والتوثيق',
          '• المراقبة المستمرة للأنظمة',
          '• الحماية من الوصول غير المصرح به أو التعديل أو الإفصاح أو إتلاف معلومات العميل',
          '• التحديثات الأمنية الدورية وإدارة الثغرات',
          'على الرغم من تطبيق الشركة لتدابير أمنية معقولة، لا يمكن ضمان أن تكون أي وسيلة تخزين أو نقل إلكتروني آمنة تمامًا.',
        ],
      },
      {
        title: '6. مسؤولية العميل تجاه حماية الخصوصية',
        paragraphs: [
          'يتحمل العملاء مسؤولية حماية معلوماتهم الشخصية.',
          'ينبغي على العملاء:',
          '• الحفاظ على سرية بيانات اعتماد حساباتهم.',
          '• عدم مشاركة رموز التحقق (OTP) مع أي شخص إطلاقًا.',
          '• تجنب مشاركة المعلومات الشخصية الحساسة عبر قنوات اتصال غير آمنة.',
          '• استخدام أجهزة موثوقة عند الوصول إلى خدمات الشركة.',
          '• الحرص على تحديث أنظمة التشغيل وبرامج مكافحة الفيروسات.',
          '• إبلاغ الشركة فورًا في حال اكتشاف وصول غير مصرح به أو نشاط مشبوه.',
        ],
      },
      {
        title: '7. الروابط الخارجية',
        paragraphs: [
          'قد يحتوي موقع الشركة الإلكتروني أو تطبيقها على روابط لمواقع إلكترونية خارجية أو خدمات تابعة لأطراف ثالثة.',
          'لا تتحمل الشركة مسؤولية ممارسات الخصوصية أو السياسات الأمنية أو محتوى مواقع الأطراف الثالثة. وعلى العملاء مراجعة سياسات الخصوصية الخاصة بتلك المواقع قبل تقديم أي معلومات شخصية.',
        ],
      },
      {
        title: '8. السرية وعدم الإفصاح',
        paragraphs: [
          'يقصد بـ "المعلومات السرية" أي معلومات يفصح عنها العميل وتُعتبر سرية وغير متاحة للعموم.',
          'تلتزم الشركة بالحفاظ على سرية هذه المعلومات وعدم الإفصاح عنها إلا في الحالات التالية:',
          '• للجهات الحكومية المخولة عند الطلب بموجب القانون المعمول به.',
          '• لمزودي الخدمات المعتمدين الذين يساعدون الشركة في إدارة أعمالها.',
          '• للشركاء التجاريين عند الضرورة لتقديم الخدمات المطلوبة.',
          '• لأغراض إحصائية أو تحليلية لا يمكن من خلالها تحديد هوية العميل.',
          '• بموافقة كتابية مسبقة من العميل.',
          'ينطبق الالتزام بالسرية على جميع أشكال الإفصاح، بما في ذلك الإفصاح الشفهي والكتابي والإلكتروني والرقمي وأي وسيلة اتصال أخرى.',
          'يجوز للشركة استخدام المعلومات السرية فقط لتحسين خدماتها وسياساتها وكفاءتها التشغيلية وأمنها وتجربة عملائها.',
        ],
      },
      {
        title: '9. ملفات تعريف الارتباط (الكوكيز) والتقنيات المماثلة',
        paragraphs: [
          'يستخدم موقع الشركة الإلكتروني ملفات تعريف الارتباط والتقنيات المماثلة من أجل:',
          '• تحسين تجربة المستخدم',
          '• تذكر تفضيلات المستخدم',
          '• تحليل حركة زوار الموقع',
          '• تحسين أداء الموقع الإلكتروني',
          '• تخصيص محتوى الموقع',
          '• تحسين فعالية التسويق عند الاقتضاء',
          'يمكن للعملاء إدارة أو تعطيل ملفات تعريف الارتباط من خلال إعدادات المتصفح الخاص بهم. وقد يؤثر تعطيل ملفات تعريف الارتباط على بعض وظائف الموقع الإلكتروني.',
        ],
      },
      {
        title: '10. أذونات تطبيق الجوال',
        paragraphs: [
          'قد يطلب تطبيق Home Care Plus الوصول إلى بعض أذونات الجهاز لتقديم خدماته بفعالية.',
          'وحسب الميزات المستخدمة، قد يطلب التطبيق الوصول إلى:',
          '• موقع الجهاز (لتحديد عناوين الخدمة وعرض الخرائط)',
          '• الكاميرا (عند الحاجة إليها لوظائف متعلقة بالخدمة)',
          '• الإشعارات (لتقديم تحديثات الحجز والتنبيهات المهمة المتعلقة بالخدمة)',
          '• الإنترنت والوصول إلى الشبكة',
          '• معلومات الجهاز اللازمة لأمن التطبيق وتشخيصه',
          'يتم طلب الأذونات فقط عند الحاجة إليها للوظيفة ذات الصلة، ويمكن للمستخدمين إدارة هذه الأذونات من خلال إعدادات أجهزتهم.',
        ],
      },
      {
        title: '11. خدمات الأطراف الثالثة',
        paragraphs: [
          'من أجل تقديم خدماتها وتحسينها، يجوز للشركة الاستعانة بمزودي خدمات موثوقين من أطراف ثالثة، بما في ذلك على سبيل المثال لا الحصر:',
          '• مزودي خدمات التوثيق',
          '• مزودي الاستضافة السحابية',
          '• خدمات الإشعارات الفورية',
          '• مزودي خدمات الخرائط وتحديد الموقع',
          '• مزودي بوابات الدفع',
          '• خدمات التحليلات والإبلاغ عن الأعطال',
          'تقوم هذه الجهات بمعالجة معلومات العميل فقط بالقدر اللازم لتقديم الخدمات نيابة عن الشركة، ويُتوقع منها الحفاظ على معايير أمنية وسرية مناسبة.',
        ],
      },
      {
        title: '12. تحديث معلومات العميل',
        paragraphs: [
          'يتحمل العملاء مسؤولية إبلاغ الشركة عند تغيير أي من معلوماتهم الشخصية.',
          'يجوز للشركة، عند الضرورة، طلب تحقق إضافي قبل تحديث معلومات العميل إذا لزم التحقق من الهوية أو في حال الاشتباه بنشاط احتيالي.',
          'يتحمل العملاء وحدهم مسؤولية أي نتائج ناجمة عن عدم الحفاظ على دقة وحداثة معلوماتهم الشخصية.',
        ],
      },
      {
        title: '13. التغييرات على سياسة الخصوصية هذه',
        paragraphs: [
          'تحتفظ الشركة بالحق في تعديل أو تحديث سياسة الخصوصية هذه في أي وقت.',
          'سيتم نشر الإصدارات المحدثة عبر الموقع الإلكتروني الرسمي للشركة أو قنوات الاتصال الرسمية الأخرى.',
          'يشكل استمرار استخدام خدمات الشركة بعد نشر سياسة الخصوصية المعدّلة قبولًا للسياسة المحدّثة.',
        ],
      },
      {
        title: '14. القانون الحاكم',
        paragraphs: [
          'تخضع سياسة الخصوصية هذه وتُفسَّر وفقًا لأنظمة ولوائح المملكة العربية السعودية.',
          'يخضع أي نزاع ينشأ عن أو يتعلق بسياسة الخصوصية هذه للاختصاص القضائي الحصري للجهات القضائية والتنظيمية المختصة داخل المملكة العربية السعودية.',
        ],
      },
      {
        title: '15. تواصل معنا',
        paragraphs: [
          'إذا كانت لديك أي أسئلة بخصوص سياسة الخصوصية هذه أو معلوماتك الشخصية، يرجى التواصل معنا عبر قنوات الاتصال الرسمية للشركة.',
          'Home Care Plus',
          'الموقع الإلكتروني: https://hcare.plus',
          'البريد الإلكتروني: admin@hcare.plus',
          'الهاتف: +919747869897',
          'العنوان: Tc 24/3088, Ushasandya Building, Kowdiar Kaudiar, Thiruvananthapuram, Kerala, 695003',
          'باستخدامك لموقع Home Care Plus الإلكتروني أو تطبيق الجوال أو أي من الخدمات التي تقدمها الشركة، فإنك تقر بأنك قرأت وفهمت ووافقت على سياسة الخصوصية هذه.',
        ],
      },
    ],
  },
};
